DECLARE @lol INT = 9;
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOL
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO


















PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLOPRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO
PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO

PRINT 'LOL ' + CAST(@lol AS VARCHAR);
--LOLOLO


































































































